name:                n-tuple
version:             0.0.3
github:              "athanclark/n-tuple"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "BSD-3"

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/athanclark/n-tuple#readme>
synopsis:            Homogeneous tuples of arbitrary length.
ghc-options:
  - -Wall

dependencies:
- base >= 4.11 && < 5
- singletons-base >= 3
- vector

library:
  source-dirs: src
